(ns sicp.chapter-1.part-2.ex-1-14
  (:require
    [sicp.chapter-1.part-2.book-1-2 :as b12]))

; Exercise 1.14
; Draw the tree illustrating the process generated by the count-change procedure of 1.2.2 in making change for 11 cents.
; What are the orders of growth of the space and number of steps used by this process as the amount to be changed increases?

(defn change
  [amount type-of-coins]
  (cond (zero? amount) 1
        (or (neg? amount) (zero? type-of-coins)) 0
        :else (+ (change amount (dec type-of-coins))
                 (change (- amount (b12/first-denomination type-of-coins)) type-of-coins))))

(defn money-change
  [amount]
  (change amount 5))
